// Generated by CIRCT firtool-1.62.0
module ALU(
  input         clock,
                reset,
  input  [3:0]  io_fn,
  input  [31:0] io_a,
                io_b,
  output [31:0] io_result
);

  wire [62:0]       _result_T_12 = {31'h0, io_a} << io_b[4:0];
  wire [15:0][31:0] _GEN =
    {{32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {$signed($signed(io_a) >>> io_b[4:0])},
     {io_a >> io_b[4:0]},
     {_result_T_12[31:0]},
     {{31'h0, io_a < io_b}},
     {{31'h0, $signed(io_a) < $signed(io_b)}},
     {io_a ^ io_b},
     {io_a | io_b},
     {io_a & io_b},
     {io_a - io_b},
     {io_a + io_b}};
  assign io_result = _GEN[io_fn];
endmodule

