// Generated by CIRCT firtool-1.62.0
module ALU(	// src/main/scala/alu.scala:6:7
  input         clock,	// src/main/scala/alu.scala:6:7
                reset,	// src/main/scala/alu.scala:6:7
  input  [3:0]  io_fn,	// src/main/scala/alu.scala:7:14
  input  [31:0] io_a,	// src/main/scala/alu.scala:7:14
                io_b,	// src/main/scala/alu.scala:7:14
  output [31:0] io_result	// src/main/scala/alu.scala:7:14
);

  wire [62:0]       _result_T_12 = {31'h0, io_a} << io_b[4:0];	// src/main/scala/alu.scala:33:28, :36:{33,37}
  wire [15:0][31:0] _GEN =
    {{32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {$signed($signed(io_a) >>> io_b[4:0])},
     {io_a >> io_b[4:0]},
     {_result_T_12[31:0]},
     {{31'h0, io_a < io_b}},
     {{31'h0, $signed(io_a) < $signed(io_b)}},
     {io_a ^ io_b},
     {io_a | io_b},
     {io_a & io_b},
     {io_a - io_b},
     {io_a + io_b}};	// src/main/scala/alu.scala:21:10, :24:14, :26:{28,33}, :27:{28,33}, :29:{28,33}, :30:{28,33}, :31:{28,33}, :33:{28,41}, :34:{28,34}, :36:{28,33}, :37:{28,33,37}, :38:{28,41,45}
  assign io_result = _GEN[io_fn];	// src/main/scala/alu.scala:6:7, :21:10, :24:14, :26:28, :27:28, :29:28, :30:28, :31:28, :33:28, :34:28, :36:28, :37:28, :38:28
endmodule

